language: python
python:
    - "3.6"

before_install:
    - python -m pip install --upgrade pip

install:
    - pip install -U Sphinx
    - pip install -U travis-sphinx

script:
    - travis-sphinx --source=example build

after_success:
    - travis-sphinx deploy