version: 2
jobs:
  build:
    working_directory: ~/sphinx_materialdesign_theme
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: 
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: build
          command: sphinx-build -b html ./example ./_build
      - run:
          name: deploy
          command: |
            pushd _build > /dev/null
            touch .nojekyll
            git init
            git add .
            git commit -m "Deploy to GitHub Pages."
            git config user.name "CircleCI User"
            git push --force --quiet "https://github.com/myyasuda/sphinx_materialdesign_theme.git" master:gh-pages > /dev/null 2>&1
            popd > /dev/null